spring.application.name=e-commerce_backend

# =====================================================
# DATABASE - SUPABASE SESSION POOLER
# =====================================================

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# FILE UPLOAD
# =====================================================

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB


# =====================================================
# REDIS
# =====================================================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# =====================================================
# MAIL
# =====================================================

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM}
app.mail.from-name=Sufi-Leather


# =====================================================
# RAZORPAY
# =====================================================

razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook_secret=${RAZORPAY_WEBHOOK_SECRET}


# =====================================================
# GOOGLE OAUTH2
# =====================================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# =====================================================
# JWT
# =====================================================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000


# =====================================================
# CLOUDINARY
# =====================================================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}